Port-Group speed updates and Interface valid-speeds issue. #67
STORDIS/orca_nw_lib pull request #71
Opened 2024-07-02 10:01 UTC by rahul-1475

Fixes #67 

issue: 

If port group speed is set to 25G , all interface in the port-group are updated to have the speed 25G, but the valid speeds and adv-speed set is still 1G and 10G which is not correct.

- The correct behaviour would be if port-group speed is updated, after receving the port-group update via gNMI subscription make an additional gnmi get to update the valid_speeds field for interface at sonic-port:sonic-port/PORT/PORT_LIST={interface_name}.

- Write test case for above.

Fixes: 
- Added interface discovery on speed update.
- Added test cases to validate. valid speeds update.

2024-07-02 10:03 UTC, rahul-1475 commented
other pull request:

https://github.com/STORDIS/orca_backend/pull/42

2024-07-03 11:12 UTC, kamalkrbh commented on pyproject.toml
> +version = "1.3.16"
@rahul-1475, Version should be +1 , similar in the backend as well.
```suggestion
version = "1.3.17"
```

2024-07-03 11:23 UTC, kamalkrbh commented on orca_nw_lib/portgroup.py
> +def get_port_group_of_interface(device_ip: str, group_id:str):
@rahul-1475 , The purpose of this function is to know the port group of a given interface. So input parameters has to be interface name instead fix has to be in the body of the function where DB function get_port_group_of_if_from_db should be called.

2024-07-03 11:27 UTC, kamalkrbh requested changes
Have a look on above comments in the files.

2024-07-04 10:48 UTC, rahul-1475 commented on orca_nw_lib/portgroup.py
> +def get_port_group_of_interface(device_ip: str, group_id:str):
- changed code get to use function get_port_group_of_if_from_db  to port group name by interface.
- created api to get prot group name by interface

2024-07-04 10:49 UTC, rahul-1475 commented on pyproject.toml
> +version = "1.3.16"
changed orca_nw_lib version to 1.3.17

2024-07-05 04:10 UTC, kamalkrbh requested changes
@rahul-1475 , Please have a look at merge conflicts.

2024-07-05 04:56 UTC, merged